global:
  domain: todo.local

frontend:
  name: todo-frontend
  image:
    repository: vikunja-frontend
    tag: "1.0.0"
    pullPolicy: Never
  service:
    type: NodePort
    port: 80
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

backend:
  name: todo-api
  image:
    repository: vikunja-api
    tag: "1.0.3"
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 3456
  hostAliases:
    - ip: "192.168.49.2"
      hostnames:
      - "keycloak.192.168.49.2.nip.io"
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  database:
    type: mysql
    host: todo-db
    user: vikunja
    database: vikunja
  auth:
    local:
      enabled: false
    openid:
      enabled: true
      name: keycloak
      authurl: "http://keycloak.192.168.49.2.nip.io/realms/todo"
      logouturl: "http://keycloak.192.168.49.2.nip.io/realms/todo/protocol/openid-connect/logout"
      clientid: todo

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: todo-frontend
            port: 80

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: false
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nginx-ingress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: todo-db

nodeSelector: {}

tolerations: []

affinity: {}
