apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: todo-db
spec:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  database: vikunja
  username: vikunja
  passwordSecretKeyRef:
    name: todo-db-secret
    key: password
  
  storage:
    size: 1Gi
  
  replicas: 1
  
  port: 3306

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    enabled: true
